image: node:20

stages:
  - test

cache:
  paths:
    - node_modules/

before_script:
  - npm ci
  - npx playwright install

test:
  stage: test
  script:
    - npm test
  artifacts:
    when: always
    paths:
      - html-report/
    expire_in: 1 week